
package xx.mx.uv.consumo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FacturasService", targetNamespace = "t4is.uv.mx/facturas", wsdlLocation = "file:/Users/vasquez/Desktop/Tec-Servicios/Inventario/src/main/resources/facturas.wsdl")
public class FacturasService
    extends Service
{

    private final static URL FACTURASSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTURASSERVICE_EXCEPTION;
    private final static QName FACTURASSERVICE_QNAME = new QName("t4is.uv.mx/facturas", "FacturasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/vasquez/Desktop/Tec-Servicios/Inventario/src/main/resources/facturas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTURASSERVICE_WSDL_LOCATION = url;
        FACTURASSERVICE_EXCEPTION = e;
    }

    public FacturasService() {
        super(__getWsdlLocation(), FACTURASSERVICE_QNAME);
    }

    public FacturasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTURASSERVICE_QNAME, features);
    }

    public FacturasService(URL wsdlLocation) {
        super(wsdlLocation, FACTURASSERVICE_QNAME);
    }

    public FacturasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTURASSERVICE_QNAME, features);
    }

    public FacturasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacturasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FacturasPortType
     */
    @WebEndpoint(name = "FacturasPort")
    public FacturasPortType getFacturasPort() {
        return super.getPort(new QName("t4is.uv.mx/facturas", "FacturasPort"), FacturasPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacturasPortType
     */
    @WebEndpoint(name = "FacturasPort")
    public FacturasPortType getFacturasPort(WebServiceFeature... features) {
        return super.getPort(new QName("t4is.uv.mx/facturas", "FacturasPort"), FacturasPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTURASSERVICE_EXCEPTION!= null) {
            throw FACTURASSERVICE_EXCEPTION;
        }
        return FACTURASSERVICE_WSDL_LOCATION;
    }

}
